[features]
seeds = true
skip-lint = false
[programs.localnet]
mono_program = "LNCRQTZfeLMFHsSggvVc9kQWb1A98PEqHxVzBraWpQs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "deploy/admin.json"

[test]
startup_wait = 60000

[scripts]
test = "sh test.sh"
