[features]
seeds = true
skip-lint = false
[programs.localnet]
mono_program = "Lag4h3EZK51MWC5L4VY7XeXmEmpo9TrAsgEhQXryHix"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "deploy/admin.json"

[test]
startup_wait = 60000

[scripts]
test = "sh test.sh"
