[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "wno5Wr2tUvFcCYbH532UxBEQ1isPeBtus1fQmkViJir"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jacksturtevant/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"