[features]
seeds = true
skip-lint = false

[programs.localnet]
mono_program = "Lag4h3EZK51MWC5L4VY7XeXmEmpo9TrAsgEhQXryHix"

[programs.mainnet]
mono_program = "LNCRQTZfeLMFHsSggvVc9kQWb1A98PEqHxVzBraWpQs"

[programs.devnet]
mono_program = "LAnCQFuCsqVgekkfYwZDoKjhZscnK1hbKuWQFNP9DXG"

[[test.validator.clone]]
address = "9zE4EQ5tJbEeMYwtS2w8KrSHTtTW4UPqwfbBSEkUrNCA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "deploy/admin.json"

[test.validator]
url = "https://api.devnet.solana.com"

#clone Buddy Program on Devnet
[[test.validator.clone]]
address = "9zE4EQ5tJbEeMYwtS2w8KrSHTtTW4UPqwfbBSEkUrNCA"


[test]
startup_wait = 60000

[scripts]
test = "sh test.sh"
